export { Student } from "./Student";
export { Course } from "./Course";
export { ClassLog } from "./ClassLog";
export { StudyGroup } from "./StudyGroup";
export { LiveLink } from "./LiveLink";
export { Review } from "./Review";
export { DialogueSubmission } from "./DialogueSubmission";
export { DialogueMark } from "./DialogueMark";
export { HandwritingSubmission } from "./HandwritingSubmission";
export { HwExamResult } from "./HwExamResult";
export { Enrollment } from "./Enrollment";
export type { IStudentDoc } from "./Student";
export type { ICourseDoc } from "./Course";
export type { IClassLogDoc } from "./ClassLog";
export type { IStudyGroupDoc } from "./StudyGroup";
export type { ILiveLinkDoc } from "./LiveLink";
export type { IReviewDoc } from "./Review";
export type { IDialogueSubmissionDoc } from "./DialogueSubmission";
export type { IDialogueMarkDoc } from "./DialogueMark";
export type { IHandwritingSubmissionDoc } from "./HandwritingSubmission";
export type { IHwExamResultDoc } from "./HwExamResult";
export type { IEnrollmentDoc } from "./Enrollment";
