import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Hind } from "next/font/google"; // <- সঠিকভাবে ইমপোর্ট করুন
import "./globals.css";
import Nav from "@/components/Nav";
import { LanguageProvider } from "../context/LanguageContext";
import ThemeProvider from "@/providers/ThemeProvider";
import { Hind_Siliguri } from "next/font/google";

// ... অন্যান্য ফন্ট

const hindSiliguri = Hind_Siliguri({
  variable: "--font-hind-siliguri", // CSS ভেরিয়েবলের নাম
  subsets: ["latin", "bengali"], // 'bengali' সাবসেট যোগ করুন
  weight: ["300", "400", "500", "600", "700"], // প্রয়োজন অনুযায়ী ওয়েট
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const hind = Hind({
  variable: "--font-hind", // <- variable নাম দিন
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Learn Chinese with Kazi Robin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${hind.variable} ${hindSiliguri.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <ThemeProvider>
          <LanguageProvider>
            <Nav />
            {children}
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
